import logging
import time

import jinja2
from natcap.invest import __version__
from natcap.invest.reports import jinja_env, raster_utils, report_constants
from natcap.invest.reports.raster_utils import RasterPlotConfig, RasterDatatype
from natcap.invest.spec import ModelSpec


LOGGER = logging.getLogger(__name__)


def report(file_registry: dict, args_dict: dict, model_spec: ModelSpec,
           target_html_filepath: str):
    """Generate an HTML summary of model results.

    Args:
        file_registry (dict): The ``natcap.invest.FileRegistry.registry``
            that was returned by the model's ``execute`` method.
        args_dict (dict): The arguments that were passed to the model's
            ``execute`` method.
        model_spec (natcap.invest.spec.ModelSpec): the model's ``MODEL_SPEC``.
        target_html_filepath (str): path to an HTML file to be generated by
            this function.

    Returns:
        ``None``
    """

    output_raster_config = RasterPlotConfig(
        raster_path=file_registry['result'],
        datatype=RasterDatatype.continuous,
        spec=model_spec.get_output('result'))

    input_raster_config = RasterPlotConfig(
        raster_path=args_dict['raster_path'],
        datatype=RasterDatatype.continuous,
        spec=model_spec.get_input('raster_path'))

    plot_config_list = [input_raster_config, output_raster_config]

    img_src = raster_utils.plot_and_base64_encode_rasters(
        plot_config_list)
    img_caption = raster_utils.caption_raster_list(
        plot_config_list)

    section_header = f'Multiplication factor {args_dict["factor"]}'

    input_raster_stats_table = raster_utils.raster_inputs_summary(
        args_dict).to_html(na_rep='')

    output_raster_stats_table = raster_utils.raster_workspace_summary(
        file_registry).to_html(na_rep='')

    env = jinja2.Environment(
        loader=jinja2.PackageLoader('invest_demo_plugin', 'templates'),
        autoescape=jinja2.select_autoescape(),
        undefined=jinja2.StrictUndefined)
    template = env.get_template('report.html')

    with open(target_html_filepath, 'w', encoding='utf-8') as target_file:
        target_file.write(template.render(
            report_script=model_spec.reporter,
            invest_version=__version__,
            report_filepath=target_html_filepath,
            model_id=model_spec.model_id,
            model_name=model_spec.model_title,
            model_description=model_spec.about,
            userguide_page=model_spec.userguide,
            timestamp=time.strftime('%Y-%m-%d %H:%M'),
            args_dict=args_dict,
            section_header=section_header,
            img_src=img_src,
            img_caption=img_caption,
            input_raster_stats_table=input_raster_stats_table,
            output_raster_stats_table=output_raster_stats_table,
            stats_table_note=report_constants.STATS_TABLE_NOTE,
            model_spec_outputs=model_spec.outputs,
            invest_reports_env=jinja_env
        ))

    LOGGER.info(f'Created {target_html_filepath}')
