[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]

[project]
name = "foo-model"
version = "0.0.1"
dependencies = ["taskgraph", "pygeoprocessing", "natcap.invest@git+https://github.com/natcap/invest#egg=feature/plugins"]

[tool.natcap.invest]
api_version = "0.0.1"
model_name = "Foo Model"  # user-facing name
pyname = "natcap.invest.foo"  # importable name
model_id = "foo"  # model identifier used internally
