[build-system]
requires = ["setuptools", "wheel", "oldest-supported-numpy"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]

[project]
name = "foo-model"
version = "0.0.1"
dependencies = [
    "pygeoprocessing>=2.4.1",
    "taskgraph",
    "natcap.invest"
]

[tool.natcap.invest]
api_version = "0.0.1"
