[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]

[project]
name = "foo-model"
version = "0.0.1"
dependencies = ["taskgraph", "pygeoprocessing", "natcap.invest"]

[tool.natcap.invest]
api_version = "0.0.1"
