[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.package-data]
foo = ["data/foo"]

[tool.setuptools]
py-modules = ["invest-foo"]

[project]
name = "invest-foo"
version = "0.0.1"
dependencies = ["taskgraph", "pygeoprocessing", "natcap.invest @ git+https://github.com/natcap/invest.git@feature/plugins"]

[tool.natcap.invest]
api_version = "0.0.1"
model_title = "Foo Model"  # user-facing name
model_id = "foo"  # model identifier used internally
conda_dependencies = [ # to install into the plugin's conda env (not available thru pip)
  "python<3.12", 
  "gdal", 
  "geotiff>=1.7.3"  # earlier versions don't support space in CONDA_PREFIX
]
